//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeSure.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LifeSure.App_GlobalResources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt debitis sint tempora. Corporis consequatur illo blanditiis voluptates aperiam quos aliquam totam aliquid rem explicabo,.
        /// </summary>
        public static string About_Description1 {
            get {
                return ResourceManager.GetString("About_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae praesentium recusandae eligendi modi hic.
        /// </summary>
        public static string About_Description2 {
            get {
                return ResourceManager.GetString("About_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can save your money..
        /// </summary>
        public static string About_Feature1 {
            get {
                return ResourceManager.GetString("About_Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production or trading of good.
        /// </summary>
        public static string About_Feature2 {
            get {
                return ResourceManager.GetString("About_Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our life insurance is flexible.
        /// </summary>
        public static string About_Feature3 {
            get {
                return ResourceManager.GetString("About_Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Range of Exploring Protection.
        /// </summary>
        public static string About_MainTitle {
            get {
                return ResourceManager.GetString("About_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        public static string About_MoreInformation {
            get {
                return ResourceManager.GetString("About_MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Our Company.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123 Street New York.USA.
        /// </summary>
        public static string AddressDetail {
            get {
                return ResourceManager.GetString("AddressDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs.
        /// </summary>
        public static string Blogs {
            get {
                return ResourceManager.GetString("Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to Our Experts.
        /// </summary>
        public static string CallExperts {
            get {
                return ResourceManager.GetString("CallExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Insurance.
        /// </summary>
        public static string CarInsurance {
            get {
                return ResourceManager.GetString("CarInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&apos;s standard dummy....
        /// </summary>
        public static string Carousel_Description {
            get {
                return ResourceManager.GetString("Carousel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string Carousel_LearnMore {
            get {
                return ResourceManager.GetString("Carousel_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Insurance Makes You Happy.
        /// </summary>
        public static string Carousel_Title {
            get {
                return ResourceManager.GetString("Carousel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Video.
        /// </summary>
        public static string Carousel_WatchVideo {
            get {
                return ResourceManager.GetString("Carousel_WatchVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To LifeSure.
        /// </summary>
        public static string Carousel_Welcome {
            get {
                return ResourceManager.GetString("Carousel_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string Common_LearnMore {
            get {
                return ResourceManager.GetString("Common_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Frequently Asked Questions.
        /// </summary>
        public static string CommonFrequentlyAskedQuestions {
            get {
                return ResourceManager.GetString("CommonFrequentlyAskedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolor amet sit justo amet elitr clita ipsum elitr est. Lorem ipsum dolor sit amet, consectetur adipiscing....
        /// </summary>
        public static string CompanyDescription {
            get {
                return ResourceManager.GetString("CompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LifeSure.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A: Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition. Organically grow the holistic world view of disruptive innovation via workplace diversity and empowerment..
        /// </summary>
        public static string FAQAnswer {
            get {
                return ResourceManager.GetString("FAQAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q: What happens during Freshers&apos; Week?.
        /// </summary>
        public static string FAQQuestion1 {
            get {
                return ResourceManager.GetString("FAQQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q: What is the transfer application process?.
        /// </summary>
        public static string FAQQuestion2 {
            get {
                return ResourceManager.GetString("FAQQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q: Why should I attend community college?.
        /// </summary>
        public static string FAQQuestion3 {
            get {
                return ResourceManager.GetString("FAQQuestion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ&apos;s.
        /// </summary>
        public static string FAQs {
            get {
                return ResourceManager.GetString("FAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 Fast Support.
        /// </summary>
        public static string Feature_FastSupport {
            get {
                return ResourceManager.GetString("Feature_FastSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea hic laborum odit pariatur....
        /// </summary>
        public static string Feature_FastSupport_Description {
            get {
                return ResourceManager.GetString("Feature_FastSupport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible Plans.
        /// </summary>
        public static string Feature_FlexiblePlans {
            get {
                return ResourceManager.GetString("Feature_FlexiblePlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea hic laborum odit pariatur....
        /// </summary>
        public static string Feature_FlexiblePlans_Description {
            get {
                return ResourceManager.GetString("Feature_FlexiblePlans_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anytime Money Back.
        /// </summary>
        public static string Feature_MoneyBack {
            get {
                return ResourceManager.GetString("Feature_MoneyBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea hic laborum odit pariatur....
        /// </summary>
        public static string Feature_MoneyBack_Description {
            get {
                return ResourceManager.GetString("Feature_MoneyBack_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted Company.
        /// </summary>
        public static string Feature_TrustedCompany {
            get {
                return ResourceManager.GetString("Feature_TrustedCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea hic laborum odit pariatur....
        /// </summary>
        public static string Feature_TrustedCompany_Description {
            get {
                return ResourceManager.GetString("Feature_TrustedCompany_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tenetur adipisci facilis cupiditate recusandae aperiam temporibus corporis itaque quis facere, numquam, ad culpa deserunt sint dolorem autem obcaecati, ipsam mollitia hic..
        /// </summary>
        public static string Features_Description {
            get {
                return ResourceManager.GetString("Features_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Provide you a Better Future.
        /// </summary>
        public static string Features_MainTitle {
            get {
                return ResourceManager.GetString("Features_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Features.
        /// </summary>
        public static string Features_Title {
            get {
                return ResourceManager.GetString("Features_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find A Location.
        /// </summary>
        public static string FindLocation {
            get {
                return ResourceManager.GetString("FindLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free: + 0123 456 7890.
        /// </summary>
        public static string FreeCall {
            get {
                return ResourceManager.GetString("FreeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string FreePhone {
            get {
                return ResourceManager.GetString("FreePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a Quote.
        /// </summary>
        public static string GetQuote {
            get {
                return ResourceManager.GetString("GetQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Insurance.
        /// </summary>
        public static string HealthInsurance {
            get {
                return ResourceManager.GetString("HealthInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life insurance is the most effective way to ensure the financial security of your loved ones. Invest in the future and live in peace..
        /// </summary>
        public static string HeroDescription {
            get {
                return ResourceManager.GetString("HeroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Insurance.
        /// </summary>
        public static string HomeInsurance {
            get {
                return ResourceManager.GetString("HomeInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Insurance.
        /// </summary>
        public static string LifeInsurance {
            get {
                return ResourceManager.GetString("LifeInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Insurance Makes You Happy.
        /// </summary>
        public static string LifeInsuranceMakesYouHappy {
            get {
                return ResourceManager.GetString("LifeInsuranceMakesYouHappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@example.com.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Us.
        /// </summary>
        public static string MailUs {
            get {
                return ResourceManager.GetString("MailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David James.
        /// </summary>
        public static string MemberName1 {
            get {
                return ResourceManager.GetString("MemberName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sarah Wilson.
        /// </summary>
        public static string MemberName2 {
            get {
                return ResourceManager.GetString("MemberName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michael Brown.
        /// </summary>
        public static string MemberName3 {
            get {
                return ResourceManager.GetString("MemberName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emily Davis.
        /// </summary>
        public static string MemberName4 {
            get {
                return ResourceManager.GetString("MemberName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Insurance Advisor.
        /// </summary>
        public static string MemberProfession1 {
            get {
                return ResourceManager.GetString("MemberProfession1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims Specialist.
        /// </summary>
        public static string MemberProfession2 {
            get {
                return ResourceManager.GetString("MemberProfession2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Assessment Manager.
        /// </summary>
        public static string MemberProfession3 {
            get {
                return ResourceManager.GetString("MemberProfession3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Relations Director.
        /// </summary>
        public static string MemberProfession4 {
            get {
                return ResourceManager.GetString("MemberProfession4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Services.
        /// </summary>
        public static string MoreServices {
            get {
                return ResourceManager.GetString("MoreServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolor amet sit justo amet elitr clita ipsum elitr est. Lorem ipsum dolor sit amet, consectetur adipiscing elit..
        /// </summary>
        public static string NewsletterText {
            get {
                return ResourceManager.GetString("NewsletterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Features.
        /// </summary>
        public static string OurFeatures {
            get {
                return ResourceManager.GetString("OurFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string OurServices {
            get {
                return ResourceManager.GetString("OurServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Page.
        /// </summary>
        public static string Page404 {
            get {
                return ResourceManager.GetString("Page404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (+012) 3456 7890.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by keyword.
        /// </summary>
        public static string SearchByKeyword {
            get {
                return ResourceManager.GetString("SearchByKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SearchModal_Close {
            get {
                return ResourceManager.GetString("SearchModal_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keywords.
        /// </summary>
        public static string SearchModal_Placeholder {
            get {
                return ResourceManager.GetString("SearchModal_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by keyword.
        /// </summary>
        public static string SearchModal_Title {
            get {
                return ResourceManager.GetString("SearchModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, eum!.
        /// </summary>
        public static string ServiceItemDescription {
            get {
                return ResourceManager.GetString("ServiceItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are constantly improving ourselves to provide our customers with the highest quality services. Together with our expert team, we create solutions tailored to your needs..
        /// </summary>
        public static string ServicesDescription {
            get {
                return ResourceManager.GetString("ServicesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LifeSure - Life Insurance.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Important FAQ&apos;s.
        /// </summary>
        public static string SomeImportantFAQs {
            get {
                return ResourceManager.GetString("SomeImportantFAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards WON.
        /// </summary>
        public static string Stats_AwardsWon {
            get {
                return ResourceManager.GetString("Stats_AwardsWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Policies.
        /// </summary>
        public static string Stats_InsurancePolicies {
            get {
                return ResourceManager.GetString("Stats_InsurancePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skilled Agents.
        /// </summary>
        public static string Stats_SkilledAgents {
            get {
                return ResourceManager.GetString("Stats_SkilledAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Members.
        /// </summary>
        public static string Stats_TeamMembers {
            get {
                return ResourceManager.GetString("Stats_TeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tenetur adipisci facilis cupiditate recusandae aperiam temporibus corporis itaque quis facere, numquam, ad culpa deserunt sint dolorem autem obcaecati, ipsam mollitia hic..
        /// </summary>
        public static string TeamDescription {
            get {
                return ResourceManager.GetString("TeamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Our Expert Team Members.
        /// </summary>
        public static string TeamMainHeading {
            get {
                return ResourceManager.GetString("TeamMainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string TeamTitle {
            get {
                return ResourceManager.GetString("TeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tenetur adipisci facilis cupiditate recusandae aperiam temporibus corporis itaque quis facere, numquam, ad culpa deserunt sint dolorem autem obcaecati, ipsam mollitia hic..
        /// </summary>
        public static string TestimonialDescription {
            get {
                return ResourceManager.GetString("TestimonialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        public static string Testimonials {
            get {
                return ResourceManager.GetString("Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Our Customers Are Saying.
        /// </summary>
        public static string TestimonialSubtitle {
            get {
                return ResourceManager.GetString("TestimonialSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem, ipsum dolor sit amet consectetur adipisicing elit. Enim error molestiae aut modi corrupti fugit eaque rem nulla incidunt temporibus quisquam..
        /// </summary>
        public static string TestimonialText {
            get {
                return ResourceManager.GetString("TestimonialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonial.
        /// </summary>
        public static string TestimonialTitle {
            get {
                return ResourceManager.GetString("TestimonialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Video.
        /// </summary>
        public static string WatchVideo {
            get {
                return ResourceManager.GetString("WatchVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To LifeSure.
        /// </summary>
        public static string WelcomeToLifeSure {
            get {
                return ResourceManager.GetString("WelcomeToLifeSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Provide Best Services.
        /// </summary>
        public static string WeProvideBestServices {
            get {
                return ResourceManager.GetString("WeProvideBestServices", resourceCulture);
            }
        }
    }
}
